// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZoomIntegrationMicroservice.Models;

namespace ZoomIntegrationMicroservice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ZoomIntegrationMicroservice.Models.AccessTokenResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("access_token")
                        .HasColumnType("text");

                    b.Property<decimal>("expires_in")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("refresh_token")
                        .HasColumnType("text");

                    b.Property<string>("scope")
                        .HasColumnType("text");

                    b.Property<string>("token_type")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("userTokens");
                });

            modelBuilder.Entity("ZoomIntegrationMicroservice.Models.CodeResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("state")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("codeTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
